package com.closedsource.qualitrack.platform.laboratory.application.internal.commandservices;

import com.closedsource.qualitrack.platform.laboratory.application.commandservices.LaboratoryCommandService;
import com.closedsource.qualitrack.platform.laboratory.domain.model.aggregates.Laboratory;
import com.closedsource.qualitrack.platform.laboratory.domain.model.commands.CreateLaboratoryCommand;
import com.closedsource.qualitrack.platform.laboratory.domain.model.commands.UpdateLaboratoryCommand;
import com.closedsource.qualitrack.platform.laboratory.domain.model.valueobjects.LaboratoryName;
import com.closedsource.qualitrack.platform.laboratory.domain.repositories.LaboratoryRepository;
import com.closedsource.qualitrack.platform.shared.application.result.ApplicationError;
import com.closedsource.qualitrack.platform.shared.application.result.Result;
import org.springframework.stereotype.Service;

/**
 * Application service implementation that executes laboratory commands.
 *
 * <p>Handles the orchestration of creating and updating laboratories, enforcing
 * unique business rules (like Name and RUC uniqueness) before persisting state.</p>
 */
@Service
public class LaboratoryCommandServiceImpl implements LaboratoryCommandService {

    private final LaboratoryRepository laboratoryRepository;

    public LaboratoryCommandServiceImpl(LaboratoryRepository laboratoryRepository) {
        this.laboratoryRepository = laboratoryRepository;
    }

    @Override
    public Result<Long, ApplicationError> handle(CreateLaboratoryCommand command) {
        try {
            var name = new LaboratoryName(command.name());

            // 1. Validate Unique Name
            if (laboratoryRepository.existsByName(name)) {
                return Result.failure(ApplicationError.conflict(
                        "Laboratory",
                        "Laboratory with name '%s' already exists".formatted(command.name())
                ));
            }

            // 2. Validate Unique RUC (Requires adding existsByRuc to LaboratoryRepository interface)
            if (laboratoryRepository.existsByRuc(command.ruc())) {
                return Result.failure(ApplicationError.conflict(
                        "Laboratory",
                        "Laboratory with RUC '%s' already exists".formatted(command.ruc())
                ));
            }

            // 3. Create and Save
            var laboratory = new Laboratory(command);
            var savedLaboratory = laboratoryRepository.save(laboratory);

            // Returns the Long ID generated by the database
            return Result.success(savedLaboratory.getId());

        } catch (IllegalArgumentException e) {
            return Result.failure(ApplicationError.validationError("Laboratory", e.getMessage()));
        } catch (Exception e) {
            return Result.failure(ApplicationError.unexpected("create-laboratory", e.getMessage()));
        }
    }

    @Override
    public Result<Laboratory, ApplicationError> handle(UpdateLaboratoryCommand command) {
        // command.laboratoryId() is now correctly inferred as Long
        var result = laboratoryRepository.findById(command.laboratoryId());

        if (result.isEmpty()) {
            return Result.failure(ApplicationError.notFound(
                    "Laboratory",
                    String.valueOf(command.laboratoryId())
            ));
        }

        var laboratoryToUpdate = result.get();
        try {
            laboratoryToUpdate.updateProfile(command);
            var updatedLaboratory = laboratoryRepository.save(laboratoryToUpdate);
            return Result.success(updatedLaboratory);
        } catch (IllegalArgumentException e) {
            return Result.failure(ApplicationError.validationError("Laboratory", e.getMessage()));
        } catch (Exception e) {
            return Result.failure(ApplicationError.unexpected("update-laboratory", e.getMessage()));
        }
    }
}