package com.closedsource.qualitrack.platform.laboratory.application.internal.commandservices;

import com.closedsource.qualitrack.platform.laboratory.application.commandservices.ProductCommandService;
import com.closedsource.qualitrack.platform.laboratory.domain.model.aggregates.PharmaceuticalProduct;
import com.closedsource.qualitrack.platform.laboratory.domain.model.commands.CreateProductCommand;
import com.closedsource.qualitrack.platform.laboratory.domain.repositories.LaboratoryRepository;
import com.closedsource.qualitrack.platform.laboratory.domain.repositories.ProductRepository;
import com.closedsource.qualitrack.platform.shared.application.result.ApplicationError;
import com.closedsource.qualitrack.platform.shared.application.result.Result;
import org.springframework.stereotype.Service;

/**
 * Application service implementation that executes pharmaceutical product commands.
 *
 * <p>Handles the orchestration of creating products, enforcing business rules
 * such as laboratory existence, name uniqueness per lab, and global catalog code uniqueness.</p>
 */
@Service
public class ProductCommandServiceImpl implements ProductCommandService {

    private final ProductRepository productRepository;
    private final LaboratoryRepository laboratoryRepository;

    public ProductCommandServiceImpl(ProductRepository productRepository, LaboratoryRepository laboratoryRepository) {
        this.productRepository = productRepository;
        this.laboratoryRepository = laboratoryRepository;
    }

    @Override
    public Result<Long, ApplicationError> handle(CreateProductCommand command) {
        // 1. Verify that the laboratory exists
        if (!laboratoryRepository.existsById(command.laboratoryId())) {
            return Result.failure(ApplicationError.notFound(
                    "Laboratory",
                    String.valueOf(command.laboratoryId())
            ));
        }

        // 2. Validate Unique Internal Catalog Code (Fail-Fast)
        if (productRepository.existsByCode(command.code())) {
            return Result.failure(ApplicationError.conflict(
                    "PharmaceuticalProduct",
                    "Product with internal code '%s' already exists".formatted(command.code())
            ));
        }

        // 3. Validate Unique Name within the same laboratory
        if (productRepository.findByNameAndLaboratoryId(command.name(), command.laboratoryId()).isPresent()) {
            return Result.failure(ApplicationError.conflict(
                    "PharmaceuticalProduct",
                    "Product with name '%s' already exists in this laboratory".formatted(command.name())
            ));
        }

        // 4. Create and Save
        try {
            var product = new PharmaceuticalProduct(command);
            var savedProduct = productRepository.save(product);

            // Returns the Long ID generated by the database
            return Result.success(savedProduct.getId());

        } catch (IllegalArgumentException e) {
            return Result.failure(ApplicationError.validationError("PharmaceuticalProduct", e.getMessage()));
        } catch (Exception e) {
            return Result.failure(ApplicationError.unexpected("create-product", e.getMessage()));
        }
    }
}