package com.closedsource.qualitrack.platform.laboratory.application.internal.commandservices;

import com.closedsource.qualitrack.platform.laboratory.application.commandservices.StaffCommandService;
import com.closedsource.qualitrack.platform.laboratory.domain.model.aggregates.StaffMember;
import com.closedsource.qualitrack.platform.laboratory.domain.model.commands.DeactivateStaffCommand;
import com.closedsource.qualitrack.platform.laboratory.domain.model.commands.RegisterStaffCommand;
import com.closedsource.qualitrack.platform.laboratory.domain.repositories.LaboratoryRepository;
import com.closedsource.qualitrack.platform.laboratory.domain.repositories.StaffRepository;
import com.closedsource.qualitrack.platform.shared.application.result.ApplicationError;
import com.closedsource.qualitrack.platform.shared.application.result.Result;
import org.springframework.stereotype.Service;

/**
 * Application service implementation that executes staff commands.
 *
 * <p>Handles the orchestration of registering and deactivating staff members,
 * enforcing business rules such as laboratory existence, email uniqueness,
 * and valid state transitions.</p>
 */
@Service
public class StaffCommandServiceImpl implements StaffCommandService {

    private final StaffRepository staffRepository;
    private final LaboratoryRepository laboratoryRepository;

    public StaffCommandServiceImpl(StaffRepository staffRepository, LaboratoryRepository laboratoryRepository) {
        this.staffRepository = staffRepository;
        this.laboratoryRepository = laboratoryRepository;
    }

    @Override
    public Result<Long, ApplicationError> handle(RegisterStaffCommand command) {
        // 1. Verify that the laboratory exists
        if (!laboratoryRepository.existsById(command.laboratoryId())) {
            return Result.failure(ApplicationError.notFound(
                    "Laboratory",
                    String.valueOf(command.laboratoryId())
            ));
        }

        // 2. Validate Unique Corporate Email (Fail-Fast)
        if (staffRepository.existsByEmail(command.email())) {
            return Result.failure(ApplicationError.conflict(
                    "StaffMember",
                    "Staff member with email '%s' already exists".formatted(command.email())
            ));
        }

        // 3. Create and Save
        try {
            var staffMember = new StaffMember(command);
            var savedStaff = staffRepository.save(staffMember);

            // Returns the Long ID generated by the database
            return Result.success(savedStaff.getId());

        } catch (IllegalArgumentException e) {
            return Result.failure(ApplicationError.validationError("StaffMember", e.getMessage()));
        } catch (Exception e) {
            return Result.failure(ApplicationError.unexpected("register-staff", e.getMessage()));
        }
    }

    @Override
    public Result<Long, ApplicationError> handle(DeactivateStaffCommand command) {
        return staffRepository.findById(command.staffMemberId()).map(staff -> {

            // 1. Prevent redundant state changes gracefully
            if (!staff.isActive()) {
                return Result.<Long, ApplicationError>failure(ApplicationError.conflict(
                        "StaffMember",
                        "Staff member is already inactive"
                ));
            }

            // 2. Deactivate and Save
            try {
                staff.deactivate();
                var savedStaff = staffRepository.save(staff);
                return Result.<Long, ApplicationError>success(savedStaff.getId());
            } catch (Exception e) {
                return Result.<Long, ApplicationError>failure(ApplicationError.unexpected("deactivate-staff", e.getMessage()));
            }

        }).orElseGet(() -> Result.failure(ApplicationError.notFound(
                "StaffMember",
                String.valueOf(command.staffMemberId())
        )));
    }
}